In [1]:
ll = [ 1,2,3,4,5]

In [2]:
import numpy as np

In [4]:
n1 =np.array(ll)

In [5]:
n1

array([1, 2, 3, 4, 5])

In [6]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [7]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [8]:
n3 = np.zeros((5,4))

In [9]:
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
n4 = np.zeros((10,10))

In [11]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
l1 = np.full((5,3),69)

In [13]:
l1

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [15]:
rr = np.arange(1,11)

In [16]:
rr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
ee = np.arange(5,55,5)

In [18]:
ee

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
tt = np.arange(7,77,7)

In [20]:
tt

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [21]:
l1 = [1,2,3,4,5]

In [22]:
uu = np.array(ll)

In [23]:
uu

array([1, 2, 3, 4, 5])

In [26]:
ff = np.array([[1,4,8,6],[6,8,4,1]])

In [27]:
ff

array([[1, 4, 8, 6],
       [6, 8, 4, 1]])

In [28]:
m1 = np.zeros((4,5))

In [29]:
m1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
k1 = np.full((2,5),4)

In [31]:
k1

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [32]:
oo = np.arange(1,11)

In [33]:
oo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
pp = np.arange(10,110,10)

In [35]:
pp


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [36]:
hh = np.random.randint(1,10,9)

In [37]:
hh

array([7, 4, 9, 1, 6, 7, 1, 4, 3])

In [38]:
n1 = np.array([[1,2,3],[7,8,9]])

In [39]:
n1

array([[1, 2, 3],
       [7, 8, 9]])

In [43]:
n1.shape

(2, 3)

In [44]:
n1.shape = (3,2)

In [45]:
n1

array([[1, 2],
       [3, 7],
       [8, 9]])

In [49]:
n1.shape=(6,1)

In [50]:
n1

array([[1],
       [2],
       [3],
       [7],
       [8],
       [9]])

In [51]:
l1 = [10,20,33]
l2 = [78,95,66]

In [53]:
np.vstack((l1,l2))

array([[10, 20, 33],
       [78, 95, 66]])

In [55]:
np.hstack((l1,l2))

array([10, 20, 33, 78, 95, 66])

In [57]:
np.column_stack((l1,l2))

array([[10, 78],
       [20, 95],
       [33, 66]])

In [1]:
import numpy as np

In [2]:
hh = np.array([10,20,30,40,50])

In [3]:
jj = np.array([40,50,60,70,80])

In [4]:
np.intersect1d(hh,jj)

array([40, 50])

In [5]:
np.setdiff1d(hh,jj)

array([10, 20, 30])

In [6]:
np.intersect1d(jj,hh)

array([40, 50])

In [7]:
np.setdiff1d(jj,hh)

array([60, 70, 80])

In [9]:
np.sum([hh,jj])

450

In [10]:
np.sum([hh,jj],axis=0)

array([ 50,  70,  90, 110, 130])

In [12]:
np.sum([hh,jj],axis=1)

array([150, 300])

In [13]:
hh = hh+1


In [14]:
hh

array([11, 21, 31, 41, 51])

In [15]:
hh = hh-1

In [16]:
hh

array([10, 20, 30, 40, 50])

In [17]:
hh = hh/2

In [18]:
hh

array([ 5., 10., 15., 20., 25.])

In [19]:
hh = hh*2

In [20]:
hh

array([10., 20., 30., 40., 50.])

In [1]:
import numpy as np

In [4]:
oo = np.array([10,20,50,60])

In [5]:
oo

array([10, 20, 50, 60])

In [6]:
np.mean(oo)

35.0

In [7]:
np.median(oo)

35.0

In [8]:
np.std(oo)

20.615528128088304

In [9]:
oo

array([10, 20, 50, 60])

In [12]:
np.save('faiz',oo)

In [13]:
np.load('faiz.npy')

array([10, 20, 50, 60])

In [14]:
'faiz.npy'

'faiz.npy'